<h1>I am in AuthDoctrine IndexController index action index.phtml</h1>

<?php echo $this->message; ?>


<hr />
<table>
	<tr>
		<th>Nome</th>
		<th>getUsrPassword</th>
		<th>getUsrEmail</th>
		<th>getUsrlId</th>
		<th>getLngId</th>
	</tr>
<?php if(isset($usuario)){ foreach ($usuario as $user) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($user->getNome());?></td>
		<td><?php //echo $this->escapeHtml($user->getUsrPassword());?></td>
		<td><?php //echo $this->escapeHtml($user->getUsrEmail());?></td>
		<td><?php //echo $this->escapeHtml($user->getUsrlId());?></td>
		<td><?php //echo $this->escapeHtml($user->getLngId());?></td>
	</tr>
<?php }} ?>
</table>