<?php
echo $this->messages;
$form = $this->form;
$form->setAttribute('action', $this->url('index/logar', array(
    'controller' => 'index',
    'action' => 'login'
)));
$form->prepare();
$this->placeholder('mostraFooter')->set('não');
echo $this->form()->openTag($form)?>


<div class="row">
	<div id="page-logo">
		<img alt="logo" class="img-responsive" src="img/logos/logo-red.png">
	</div>
</div>
<div class="row">
	<div class=" col-lg-4"></div>
	<div class=" col-lg-4">
		<div class="panel">
			<div class="panel-heading">
				<div class="panel-title">
					<h3>
						<i class="glyphicon glyphicon-log-in"></i> <?php echo $this->translate('Login'); ?></h3>
				</div>
			</div>
			<div class="panel-body">
        		<?php if ($this->formElementErrors($form->get('nome'))): ?>
            	<div class="alert alert-warning alert-error col-lg-12">
        			<?php echo $this->formElementErrors($form->get('nome'))?>
            	</div>
        		<?php endif; ?>
        		
        		<div class="form-group">
					<div class="control-label col-lg-12">
        			 <?php echo $this->formLabel($form->get('nome'))?>
        		    </div>
					<div class="col-lg-12">
        			 <?php echo $this->formInput($form->get('nome'))?>
        		    </div>
				</div>

				<div class="form-group">
					<div class="control-label col-lg-12">
        			 <?php echo $this->formLabel($form->get('password'))?>
        		  </div>
					<div class="col-lg-12">
        			 <?php echo $this->formInput($form->get('password'))?>
        		  </div>
				</div>

				<div class="form-group">
					<div class="control-label col-lg-12"></div>
					<div class="col-lg-12">
        			<?php if ($this->redirect): ?>
            			<input type="hidden" name="redirect"
							value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        			<?php endif ?>
        			<button type="submit" name="submit"
							class="btn btn-red btn-gradient" value=""><?php echo $this->translate('Sign In'); ?></button>
					</div>
				</div>

				<div class="form-group">
					<div class="control-label col-lg-6">
						<label for="nome">Lembrar</label>
					</div>
					<div class="col-lg-6">
        		          <?php echo $this->formcheckbox($form->get('rememberme'))?>
        		     </div>
				</div>
        
        		<?php echo $this->form()->closeTag()?>
        
        		<?php if ($this->enableRegistration) : ?>
        		    <?php echo $this->translate('Not registered?'); ?> <a
					href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
        		<?php endif; ?>
	    </div>
			<div class="panel-footer">
				<p>
					<a
						href="<?php echo $this->url('registration', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a>
					| <a
						href="<?php echo $this->url('registration/forgotten-password', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
				</p>
			</div>
		</div>

	</div>
	<div class=" col-lg-4"></div>
</div>

<?php echo $this->form()->closeTag()?>
</div>

<?php
// view helper
if ($user = $this->identity()) {
    echo 'Logged in as ' . $this->escapeHtml($user->getNome());
    ?>
 |
<a
	href="<?php echo $this->url('index/logout', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
<?php
} else {
    echo 'Not logged in';
}
?>