<?php
$form = $this->form;
// $form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
$form->prepare();
echo $this->form()->openTag($form);
//echo $this->formRow($form->get('email'));
//echo $this->formSubmit($form->get('submit'));

?>
<div class="col-md-3"></div>
<div class="col-md-4 col-lg-5"
	style="margin-left: auto; margin-right:auto;">
	<div class="panel">
		<div class="panel-heading">
			<div class="panel-title">
				<i class="fa fa-pencil"></i> Recuperar Senha
			</div>
		</div>
		<div class="panel-body">
			<form method="get" id="altForm" class="cmxform"
				novalidate="novalidate">

				<hr class="short">
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-envelope-o"></i> </span>
					    <?php echo $this->formInput($form->get('email')->setAttributes(array('placeholder'=>'Digite o Email')))?>	
					</div>
										    <?php echo $this->losFormElementErrors($form->get('email'), array('class' => 'help-block'))?>
					</div>
				<div class="form-group">
					<input type="submit" value="Submit" class="submit btn btn-blue">
				</div>
			</form>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>