<div class="row">
	<div class=" col-lg-1"></div>
	<div class=" col-lg-10">
		<div class="panel">
			<div class="panel-heading">
				<div class="panel-title">
					<h3>
						<i class="glyphicon glyphicon-list"></i> <?php echo $this->translate('Adicionar Serviço'); ?></h3>
				</div>
			</div>
			<div class="panel-body">
                    <?php echo $this->losForm($this->entityForm); ?>
            </div>
		</div>
	</div>
</div>
