<?php echo $this->doctype(); ?>
<html>
<head>
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8" />
<?php echo $this->headTitle('Zf2 tutorial')->setSeparator(' - ')->setAutoEscape(false)?>
<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>


<!-- Font CSS  -->
<link rel="stylesheet" type="text/css"
	href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700" />
<!-- Core CSS  -->
<link rel="stylesheet" type="text/css"
	href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css"
	href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
<link rel="stylesheet" type="text/css"
	href="fonts/glyphicons_pro/glyphicons.min.css" />


<!-- Theme CSS -->
<!-- Demonstration CSS -->
<!-- Your Custom CSS -->
<!-- Favicon -->
<?php
echo $this->losHeadLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/favicon.ico'
))
    ->appendStylesheet($this->basePath() . '/css/theme.css')
    ->appendStylesheet($this->basePath() . '/css/pages.css')
    ->appendStylesheet($this->basePath() . '/css/plugins.css')
    ->appendStylesheet($this->basePath() . '/css/responsive.css')
    ->appendStylesheet($this->basePath() . '/css/demo.css')
    ->appendStylesheet($this->basePath() . '/css/custom.css')
    ->prependBootstrap()
    ->appendFontAwesome();
?>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body class="login-page">
	<a href="<?php echo $this->url('home') ?>" id="return-arrow"> <i
		class="fa fa-arrow-circle-left fa-3x text-red2"></i> <span> Retornar <br />
			ao site
	</span>
	</a>

	<!-- Start: Main -->
	<div id="main">
		<div class="container">
        <?php echo $this->content; ?>
  </div>
	</div>
	<!-- End: Main -->

	<!-- Core Javascript - via CDN -->
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script
		src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
	<script
		src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

	<!-- Theme Javascript -->
	<script type="text/javascript" src="js/uniform.min.js"></script>
	<script type="text/javascript" src="js/main.js"></script>
	<script type="text/javascript" src="js/custom.js"></script>
	<script type="text/javascript">

jQuery(document).ready(function() {

	// Init Theme Core 	  
	Core.init();   
	
});

</script>
</body>
</html>